config/routes.rb
Rails.application.routes.draw do
  resources :firmas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/firma.rb
class Firma < ApplicationRecord
    validates :nombre, :saludo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/firmas_controller.rb
class FirmasController < ApplicationController
  before_action :set_firma, only: %i[ show edit update destroy ]

  # GET /firmas or /firmas.json
  def index
    @firmas = Firma.all
  end

  # GET /firmas/1 or /firmas/1.json
  def show
  end

  # GET /firmas/new
  def new
    @firma = Firma.new
  end

  # GET /firmas/1/edit
  def edit
  end

  # POST /firmas or /firmas.json
  def create
    @firma = Firma.new(firma_params)

    respond_to do |format|
      if @firma.save
        format.html { redirect_to firma_url(@firma), notice: "Firma ha sido creada." }
        format.json { render :show, status: :created, location: @firma }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @firma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firmas/1 or /firmas/1.json
  def update
    respond_to do |format|
      if @firma.update(firma_params)
        format.html { redirect_to firma_url(@firma), notice: "Firma ha sido editada." }
        format.json { render :show, status: :ok, location: @firma }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @firma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firmas/1 or /firmas/1.json
  def destroy
    @firma.destroy

    respond_to do |format|
      format.html { redirect_to firmas_url, notice: "Firma ha sido eliminada." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firma
      @firma = Firma.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def firma_params
      params.require(:firma).permit(:nombre, :saludo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firmas_helper.rb
module FirmasHelper
end

app/views/firmas/_firma.html.erb
<div id="<%= dom_id firma %>">
  <p>
    <strong>Nombre:</strong>
    <%= firma.nombre %>
  </p>

  <p>
    <strong>Saludo:</strong>
    <%= firma.saludo %>
  </p>

</div>

app/views/firmas/_form.html.erb
<%= form_with(model: firma) do |form| %>
  <% if firma.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(firma.errors.count, "error") %> prohibited this firma from being saved:</h2>

      <ul>
        <% firma.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre, class: 'form-control form-control-lg' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :saludo, style: "display: block" %>
    <%= form.text_area :saludo, class: 'form-control form-control-lg' %>
  </div>

  <div class="form-group mt-3">
    <%= form.submit class: "btn btn-primary btn-lg", value: "Crear Firma" %> 
    <%= link_to "Volver al libro de visitas", firmas_path, class: "btn btn-outline-primary btn-lg" %>
  </div>
<% end %>

app/views/firmas/edit.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title">Editar firma</h1>
    </div>
    <div class="card-body">
      <%= render "form", firma: @firma %>
    </div>
  </div>
</div>

app/views/firmas/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="col-lg-8 mx-auto">
  <h1>Libro de visitas</h1>
  <%= link_to "Nueva firma", new_firma_path, class: "btn btn-primary btn-lg mb-3" %>
  <div id="firmas">
    <% @firmas.each do |firma| %>
    <div class="card shadow mb-3">
      <div class="card-body">
        <%= render firma %>
        <p>
          <%= link_to "Ver esta firma", firma, class: "btn btn-primary" %>
        </p>
      </div>
    </div>
     
    <% end %>
  </div>
</div>

app/views/firmas/new.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title">Nueva firma</h1>
    </div>
    <div class="card-body">
      <%= render "form", firma: @firma %>
    </div>
  </div>
</div>

app/views/firmas/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card shadow mb-3">
  <div class="card-body">
    <%= render @firma %>
  </div>

<div class="mt-1">
  <%= link_to "Editar esta firma", edit_firma_path(@firma), class:"btn btn-warning" %>
  <%= link_to "Volver al libro de visitas", firmas_path, class:"btn btn-outline-primary" %>

  <%= button_to "Eliminar esta firma", @firma, method: :delete, class: "btn btn-danger mt-3 mb-3" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Libro de visitas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>